### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by zhofre** [mthamil/Autofac.Extras.Ordering#1]
The current Nuget doesn't support .NET Standard.
I've pulled the sources and the current code requires no modification, only to be build as a netstandard library.

**Comment by mthamil** [comment]
Thank you for bringing this to my attention. I will do this as soon as I can. In the meantime, you can add 
```xml
<PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
```
to your project since it is a PCL. I just tested it, and it worked.
