### ISSUE TITLE
Update to Autofac 6 and .NET Standard 2.0

### ISSUE THREAD

**Issue by ladenedge** [mthamil/Autofac.Extras.Ordering#3]
Having been built against Autofac 4, this otherwise excellent library is giving me the following exception when paired with Autofac 6:

> System.TypeLoadException: Method 'RegistrationsFor' in type 'Autofac.Extras.Ordering.OrderedRegistrationSource' from assembly 'Autofac.Extras.Ordering, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Rebuilding against Autofac 6 (and .NET Standard 2.0) solves the problem.

**Comment by mthamil** [comment]
Thank you for submitting this issue and contributing! I will review your pull request.
