### ISSUE TITLE
Can `OrderBy()` be made optional?

### ISSUE THREAD

**Issue by rcdailey** [mthamil/Autofac.Extras.Ordering#6]
Is it possible to make the "default order" be the order of registration? Basically do `RegisterType()` by itself in the order I want?

**Comment by mthamil** [comment]
You can use `OrderByRegistration()` to avoid providing an explicit order, but I'm not sure if I can, or want to, apply ordering to all registrations. It's something I can look into, I suppose.

**Comment by rcdailey** [comment]
Honestly I'd be OK with an extension method too. Something like:

```cs
builder.RegisterOrdered<MyClass>().As<IMyClass>();
```

**Comment by rcdailey** [comment]
I just noticed from your unit tests that you can do this too. This is actually pretty clean and I'll go with this. Thanks for the inspiration!

```cs
builder.RegisterTypes(
        typeof(IncludeExcludeFilter),
        typeof(StrictNegativeScoresFilter))
    .As<IReleaseProfileFilter>()
    .OrderByRegistration();
```

**Comment by mthamil** [comment]
Glad I could help! I know the documentation isn't exactly thorough.
